// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl1xzaC-tmOu-cn5oH7bxKMQpKHIBURBo',
    appId: '1:496279702307:web:02b75df9c1e06abd441a96',
    messagingSenderId: '496279702307',
    projectId: 'booklibrary-9dc9c',
    authDomain: 'booklibrary-9dc9c.firebaseapp.com',
    storageBucket: 'booklibrary-9dc9c.appspot.com',
    measurementId: 'G-JZPPFNMDLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YtWNdNwC1mAq1JrcOhGMnwSk2hrV3qE',
    appId: '1:496279702307:android:9aeea0ed1525c350441a96',
    messagingSenderId: '496279702307',
    projectId: 'booklibrary-9dc9c',
    storageBucket: 'booklibrary-9dc9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVpgaTvUehQaOvpTkwLEjvLMrjw4mV6g',
    appId: '1:496279702307:ios:dea8348feefd0b64441a96',
    messagingSenderId: '496279702307',
    projectId: 'booklibrary-9dc9c',
    storageBucket: 'booklibrary-9dc9c.appspot.com',
    iosClientId: '496279702307-opctjfcq2nkj0hbhdker6485lvadb8m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.booklibrary',
  );
}
